package questsheets.reference;

import cpw.mods.fml.common.ModMetadata;

import java.util.Arrays;

public class Metadata
{
    public static ModMetadata init(ModMetadata metadata)
    {
        metadata.modId = Reference.ID;
        metadata.name = Reference.NAME;
        metadata.description = "Adds human-readable JSON import/export of HQM quest pages.";
        metadata.url = "";
        metadata.version = Reference.VERSION_FULL;
        metadata.authorList = Arrays.asList("hilburn");
        metadata.credits = "";
        metadata.autogenerated = false;
        return metadata;
    }
}
